name: Docker ECR
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: upload image to ECR
      uses: ./
      with:
        access_key: ${{ secrets.aws_access_key_id }}
        secret_key: ${{ secrets.aws_secret_access_key }}
        registry: ${{ secrets.registry }}
        cache_from: ${{ secrets.cache }}
        repo: api-sample
        region: ap-northeast-1
        auto_tag: true
        daemon_off: false
        dockerfile: example/Dockerfile
        context: example
